# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.NET Core app to Azure Web App - purnamyogashala

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Use the .NET SDK version your project targets

      - name: Restore dependencies
        run: dotnet restore ./learningapp/learningapp.csproj

      - name: Build
        run: dotnet build ./learningapp/learningapp.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./learningapp/learningapp.csproj --configuration Release --output ./published

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ./published

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FB1C2B6199FC4F49B0E9B25DE98959EB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6C9E76B0BF1542059F6AFA8D6C107629 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D98FE58E3664423E91134E8BB3F049E3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'purnamyogashala'
          slot-name: 'Production'
          package: .
